---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxysql-shared
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/L0rdWyd3r/argolearn.git
    targetRevision: HEAD
    path: envs/staging/proxysql-shared
    helm:
      valueFiles:
        - config.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

