apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxysql-shared
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/L0rdWyd3r/argolearn.git
    targetRevision: HEAD
    path: envs/staging/proxysql-shared
    helm:
      values: |
        cluster_username: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.cluster_username | b64dec }}
        cluster_password: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.cluster_password | b64dec }}
        monitor_username: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.monitor_username | b64dec }}
        monitor_password: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.monitor_password | b64dec }}

        proxysql:
          mysql:
            users:
              - username: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.iam_username | b64dec }}
                password: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.iam_password | b64dec }}
              - username: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.flip_username | b64dec }}
                password: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.flip_password | b64dec }}
              - username: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.manager_username | b64dec }}
                password: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.manager_password | b64dec }}
              - username: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.notifications_username | b64dec }}
                password: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.notifications_password | b64dec }}
              - username: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.stores_username | b64dec }}
                password: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.stores_password | b64dec }}
            servers: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.mysql_servers | b64dec }}

        image:
          repository: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.image_repository | b64dec }}
          tag: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.image_tag | b64dec }}
          pullPolicy: {{ (lookup "v1" "Secret" "dev" "proxysql-values").data.image_pullPolicy | b64dec }}
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
