{{/*
  Bezpieczne „wyciąganie” wartości z .Values.
*/}}
{{- $vals      := .Values -}}
{{- $proxysql  := default (dict) $vals.proxysql -}}
{{- $mysql     := default (dict) $proxysql.mysql -}}
{{- $users     := default (list) $mysql.users -}}
{{- $servers   := default (list) $mysql.servers -}}
{{- $replicas  := default 1      $vals.replicaCount | int -}}

{{- $cUser := default "cluster"          $vals.cluster_username -}}
{{- $cPass := default "cluster_password" $vals.cluster_password -}}
{{- $mUser := default "proxysql"         $vals.monitor_username -}}
{{- $mPass := default "monitor_password" $vals.monitor_password -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql.fullname" . }}
type: Opaque
stringData:
  proxysql.conf: |
    datadir="/datadir"
    errorlog="/var/lib/proxysql/proxysql.log"

    admin_variables=
    {
        admin_credentials="admin:admin;{{ $cUser }}:{{ $cPass }}"
        mysql_ifaces="0.0.0.0:6032"
        cluster_username="{{ $cUser }}"
        cluster_password="{{ $cPass }}"
        cluster_check_interval_ms=200
        # …(reszta bez zmian)…
    }

    mysql_variables=
    {
        # …inne zmienne…
        monitor_username="{{ $mUser }}"
        monitor_password="{{ $mPass }}"
        # …(reszta bez zmian)…
    }

    mysql_users =
    (
      {{- $totalUsers := len $users -}}
      {{- range $index, $u := $users }}
      {
        username="{{ required "mysql username is required!" $u.username }}"
        password="{{ required "mysql password is required!" $u.password }}"
        use_ssl=0
        default_hostgroup={{ add1 (int (default 9 $u.readOnly)) }}
        transaction_persistent=1
        active=1
        max_connections={{ default 10000 $u.maxConnections }}
      }{{- if lt (add1 $index) $totalUsers -}},{{- end }}
      {{- end }}
    )

    mysql_servers =
    (
      {{- $totalServers := len $servers -}}
      {{- range $index, $s := $servers }}
      {
        hostgroup_id={{ if or $s.isWriter (kindIs "invalid" $s.isWriter) }}10{{ else }}1{{ end }}
        hostname="{{ required "mysql server hostname is required!" $s.hostname }}"
        port={{ default 3306 $s.port }}
        use_ssl=1
      }{{- if lt (add1 $index) $totalServers -}},{{- end }}
      {{- end }}
    )

    # …pozostała część pliku bez zmian…

    proxysql_servers =
    ({{ range $i, $e := until $replicas }}
    {
    hostname="{{ include "proxysql.fullname" $ }}-announce-{{ $i }}"
    port=6032
    weight=0
    comment="announce-{{ $i }}"
    },{{ end }}
    )

