{{/*
  Helpery z domyślnymi wartościami.
  Dzięki temu .Values.service może być pusty / nil.
*/}}
{{- $svc      := default (dict) .Values.service -}}
{{- $type     := default "ClusterIP" $svc.type   -}}
{{- $port     := default 3306        $svc.port   | int -}}
{{- $replicas := default 1           .Values.replicaCount | int -}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
{{ include "proxysql.labels" . | indent 4 }}
spec:
  type: {{ $type }}
  ports:
    - port: {{ $port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
    - port: 6032
      targetPort: proxysql-admin
      protocol: TCP
      name: proxysql-admin
  selector:
    app.kubernetes.io/name: {{ include "proxysql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

{{/*  drugi Service per‑pod */}}
{{- range $i, $e := until $replicas }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxysql.fullname" $ }}-announce-{{ $i }}
  labels:
{{ include "proxysql.labels" $ | indent 4 }}
spec:
  type: {{ $type }}
  ports:
    - port: {{ $port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
    - port: 6032
      targetPort: proxysql-admin
      protocol: TCP
      name: proxysql-admin
  selector:
    app.kubernetes.io/name: {{ include "proxysql.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ include "proxysql.fullname" $ }}-{{ $i }}
{{- end }}

