---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxysql.fullname" $ }}
  labels:
{{ include "proxysql.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
    - port: 6032
      targetPort: proxysql-admin
      protocol: TCP
      name: proxysql-admin
  selector:
    app.kubernetes.io/name: {{ include "proxysql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

{{ range $i, $e := until (int .Values.replicaCount) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxysql.fullname" $ }}-announce-{{ $i }}
  labels:
{{ include "proxysql.labels" $ | indent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
    - port: 6032
      targetPort: proxysql-admin
      protocol: TCP
      name: proxysql-admin
  selector:
    app.kubernetes.io/name: {{ include "proxysql.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ include "proxysql.fullname" $ }}-{{ $i }}
{{ end }}
