cluster_username: cluster
cluster_password: ""
monitor_username: proxysql
monitor_password: ""

image:
  repository: 911111111111.dkr.ecr.eu-west-1.amazonaws.com/dev/infra/proxysql
  tag: 2.7.3
  pullPolicy: Always

proxysql:
  mysql:
    servers:
      - hostname: 10.101.0.189
        isWriter: true
        port: 3306
      - hostname: 10.101.1.221
        isWriter: false
        port: 3306
      - hostname: 10.101.2.56
        isWriter: false
        port: 3306
    users:
      - username: iam
        password: MH2A
      - username: flip
        password: zRl5XcV
      - username: manager
        password: MHDVoAz
      - username: notifications
        password: a1EaE
      - username: stores
        password: JQvM66BD

replicaCount: 1

service:
  type: ClusterIP
  port: 3306

